config/routes.rb
Rails.application.routes.draw do

  root to: "public/homes#top", as: 'top'

  devise_for :admins, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_scope :user do
    post 'public/guest_sign_in', to: 'public/sessions#guest_sign_in', as: 'guest_sign_in'
  end

  scope module: :public do
    resources :play_histores, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      resource :favorites, only: [:create, :destroy]
    end
    resources :recruits, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      resources :comments, only: [:create, :update, :destroy]
    end
    resources :users, only: [:index, :show, :edit, :update, :destroy]do
      resource :follows, only: [:create, :destroy]
      get 'followings' => 'follows#followings', as: 'followings'
      get 'followers' => 'follows#followers', as: 'followers'
    end

    get 'following_users' => 'follows#index', as: 'following_users'
    get 'drafts', to: 'recruits#drafts', as: 'drafts'
    get 'favorites', to: 'favorites#index', as: 'favorites'
    # get 'search_play_histores'=>'playHistores#search_play_histores', as: 'search_play_histores'
  #   post '/user/:/users/:user_id/follows'
  #   patch '/users/:user_id/follows'
  #   get '/users/confirm', to: 'users#confirm', as: 'confirm'
  #   patch '/users/cancel', to: 'users#cancel', as: 'cancel'

  end

  namespace :admin do
    resources :play_histores, only: [:index,:show, :edit, :update, :destroy]
    resources :titles, only: [:index, :create, :show, :edit, :update, :destroy]
    resources :users, only: [:index, :show, :edit, :update, :destroy]
    resources :recruits, only: [:index,:show,:edit, :update, :destroy] do
      resources :comments, only: [:destroy]
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/controllers/admin/play_histores_controller.rb
class Admin::PlayHistoresController < ApplicationController
  def index
    if params[:search] == nil
      @play_histores = PlayHistory.all
    elsif params[:search] == ''
      @play_histores = PlayHistory.all
    else
      @play_histores = PlayHistory.where("scenario_name LIKE ? ",'%' + params[:search] + '%')
    end
  end

  def show
    @user = PlayHistory.find(params[:id])
    @play_history = PlayHistory.find(params[:id])
  end

  def edit
    @play_history = PlayHistory.find(params[:id])
  end

  def update
    @play_history = PlayHistory.find(params[:id])
    if @play_history.update(play_history_params)
      redirect_to admin_play_histore_path(@play_history.id)
    else
      render :edit
    end
  end

  def destroy
    @play_history = PlayHistory.find(params[:id])
    @play_history.destroy
    redirect_to admin_play_histores_path
  end

  private

  def play_history_params
    params.require(:play_history).permit(:title_id, :scenario_name, :play_style, :memo, :secret_memo, :is_active)
  end
end

app/helpers/admin/play_histores_helper.rb
module Admin::PlayHistoresHelper
end

app/views/admin/play_histores/edit.html.erb
<div class="container">
  <div class="d-flex align-items-center p-3 my-2">
    <h4 class="border-bottom border-primary border-3 page-title">プレイ履歴編集</h4>
  </div>

  <div class="my-2 p-3 bg-white rounded shadow-sm">
    <%= form_with model: @play_history, url: admin_play_histore_path do |f| %>
      <table class="table table-borderless">
        <tr class="border-bottom border-gray pb-2 my-3">
          <th>シナリオ名(必須)</th>
          <td><%= f.text_field :scenario_name, size: "50x1" %></td>
        </tr>
        <tr class="border-bottom border-gray pb-2 mb-3">
          <th>タイトル</th>
          <td><%= f.collection_select(:title_id, Title.all, :id, :name, {}, {class:"select-box"}) %></td>
        </tr>
        <tr class="border-bottom border-gray pb-2 mb-3">
          <th>プレイ方法</th>
          <td>
            <%= f.radio_button :play_style, PlayHistory.play_styles.key(0), checked: true %>
            <%= f.label :play_style_gm, PlayHistory.play_styles_i18n[:gm] %>
            <%= f.radio_button :play_style, PlayHistory.play_styles.key(1) %>
            <%= f.label :play_style_player, PlayHistory.play_styles_i18n[:player] %>
          </td>
        </tr>
        </tr>
        <tr class="border-bottom border-gray pb-2 my-3">
          <th>メモ</th>
          <td><%= f.text_area :memo, placeholder: play_history_memo, size: "60x20" %></td>
        </tr>
        <tr class="border-bottom border-gray pb-2 my-3">
          <th>ネタバレモ</th>
          <td><%= f.text_area :secret_memo, placeholder: play_history_memo, size: "60x20" %></td>
        </tr>
        <tr class="border-bottom border-gray pb-2 my-3">
          <th>公開設定</th>
          <td>
            <%= f.radio_button :is_active, true, checked: true %>
            <%= f.label :is_active_status_true, "公開" %>
            <%= f.radio_button :is_active, false %>
            <%= f.label :is_active_status_false, "非公開" %>
          </td>
        </tr>
        <tr class="pb-2-my-3">
          <th></th>
          <td>
            <div class="text-right">
              <%= f.submit "更新", class: "btn btn-primary" %>
            </div>
          </td>
        </tr>
      </table>
    <% end %>
  </div>
</div>

app/views/admin/play_histores/index.html.erb
<div class="container">
  <div class="d-flex align-items-center px-3 pt-3 mt-2">
    <h4 class="border-bottom border-primary border-3 page-title">プレイ履歴</h4>
  </div>

  <div class="d-flex align-items-center px-3 pb-2 my-2">
    <div class="ml-auto">
      <%= form_tag({controller:"play_histores",action:"index"}, method: :get) do %>
        <%= text_field_tag :search %>
        <%= submit_tag '検索する' %>
      <% end %>
      <%= link_to "条件クリア", admin_play_histores_path, class: "btn btn-secondary mt-1" %>
    </div>
  </div>
  <div class="my-2 p-3 bg-white rounded shadow-sm">
    <table class="table">
      <thead class="thead-light">
        <tr>
          <th>ユーザー</th><th>シナリオ名</th><th>タイトル</th><th>担当</th><th>登録日</th>
        </tr>
      </thead>
      <tbody>
        <% @play_histores.each do |play_history| %>
          <tr>
            <td class="align-middle"><%= link_to admin_user_path(play_history.user_id) do %>
                <%= image_tag play_history.user.get_profile_image.variant(resize: "60x60!") %>
                <%= play_history.user.name %>
              <% end %>
            </td>
            <td class="align-middle">
              <%= link_to admin_play_histore_path(play_history.id) do %>
                <%= play_history.scenario_name %>
              <% end %>
            </td>
            <td class="align-middle">
              <span class="p-2 text-dark"><%= play_history.title.name %></span>
            </td>
            <td class="align-middle"><%= play_history.play_style_i18n %></td>
            <td class="align-middle"><%= play_history.created_at.strftime('%Y/%m/%d') %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/play_histores/show.html.erb
<div class="container mb-3">
  <div class="d-flex align-items-center p-3 my-2">
    <h4 class="border-bottom border-primary border-3 page-title">プレイ履歴詳細</h4>
  </div>
  <div class="ml-auto">
    <div class="d-flex align-items-center p-3 my-3 text-light bg-gray rounded shadow-sm">
      <%= image_tag @play_history.user.get_profile_image.variant(resize: "80x80!") %>
      <h3>
         <%= @play_history.user.name %>
      </h3>
    </div>
  </div>

  <div class="my-3 p-3 bg-white rounded shadow-sm">
    <h3 class="d-inline">
      <%= @play_history.scenario_name %>
      <% if @play_history.is_active == false %>
        <i class="fa-solid fa-lock"></i>
      <% end %>
    </h3>
    <span class="sm p-2 text-dark"><%= @play_history.title.name %></span>　担当：<%= @play_history.play_style_i18n %>

    <div class="mb-4">
      <h6 class="border-bottom border-gray pb-2 my-4"><strong>メモ</strong></h6>
      <%= safe_join(@play_history.memo.split("\n"), tag(:br) ) %>
    </div>

    <div class="mb-2">
        <details close><summary class="border-bottom border-gray pb-2 my-4"><h6 class="d-inline"><strong>ネタバレメモ</strong></summary></h6>
        <%= safe_join(@play_history.secret_memo.split("\n"), tag(:br) ) %></details>
    </div>
    <%= link_to "編集", edit_admin_play_histore_path(@play_history.id), class: "btn btn-secondary" %>
    <%= link_to "削除", admin_play_histore_path(@play_history.id), class: "btn btn-danger", method: :delete, data: {confirm: "削除しますか？"} %>
  </div>
</div>