config/routes.rb
Rails.application.routes.draw do

  root to: "public/homes#top", as: 'top'

  devise_for :admins, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_scope :user do
    post 'public/guest_sign_in', to: 'public/sessions#guest_sign_in', as: 'guest_sign_in'
  end

  scope module: :public do
    resources :play_histores, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      resource :favorites, only: [:create, :destroy]
    end
    resources :recruits, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      resources :comments, only: [:create, :update, :destroy]
    end
    resources :users, only: [:index, :show, :edit, :update, :destroy]do
      resource :follows, only: [:create, :destroy]
      get 'followings' => 'follows#followings', as: 'followings'
      get 'followers' => 'follows#followers', as: 'followers'
    end

    get 'following_users' => 'follows#index', as: 'following_users'
    get 'drafts', to: 'recruits#drafts', as: 'drafts'
    get 'favorites', to: 'favorites#index', as: 'favorites'
    # get 'search_play_histores'=>'playHistores#search_play_histores', as: 'search_play_histores'
  #   post '/user/:/users/:user_id/follows'
  #   patch '/users/:user_id/follows'
  #   get '/users/confirm', to: 'users#confirm', as: 'confirm'
  #   patch '/users/cancel', to: 'users#cancel', as: 'cancel'

  end

  namespace :admin do
    resources :play_histores, only: [:index,:show, :edit, :update, :destroy]
    resources :titles, only: [:index, :create, :show, :edit, :update, :destroy]
    resources :users, only: [:index, :show, :edit, :update, :destroy]
    resources :recruits, only: [:index,:show,:edit, :update, :destroy] do
      resources :comments, only: [:destroy]
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/recruit.rb
class Recruit < ApplicationRecord
  validates :scenario_name, presence: true, length: { minimum: 1, maximum: 40 }
  validates :message, presence: true

  enum status: { published: 0, draft: 1 }

  belongs_to :user
  belongs_to :title
  has_many :comments, dependent: :destroy
end

app/controllers/admin/recruits_controller.rb
class Admin::RecruitsController < ApplicationController
  def index
    if params[:search] == nil
      @recruits = Recruit.all
    elsif params[:search] == ''
      @recruits = Recruit.all
    else
      @search_title = params[:search]
      @recruits = Recruit.where(title_id: @search_title )
    end
  end

  def show
    @recruit = Recruit.find(params[:id])
    @comment = Comment.new
  end

  def edit
    @recruit = Recruit.find(params[:id])
  end

  def update
    @recruit = Recruit.find(params[:id])
    if @recruit.update(recruit_params)
      redirect_to admin_recruit_path(@recruit.id)
    else
      render :edit
    end
  end

  def destroy
    recruit = Recruit.find(params[:id])
    recruit.destroy
    redirect_to admin_recruits_path(params[:recruit_id])
  end

  private

  def recruit_params
    params.require(:recruit).permit(:title_id, :scenario_name, :message, :recruit_status, :status)
  end
end

app/helpers/admin/recruits_helper.rb
module Admin::RecruitsHelper
end

app/views/admin/recruits/edit.html.erb
<div class="container">
  <div class="d-flex align-items-center p-3 my-2">
    <h4 class="border-bottom border-primary border-3 page-title">メンバー募集編集</h4>
  </div>

  <div class="my-2 p-3 bg-white rounded shadow-sm">
    <%= form_with model: @recruit, url: admin_recruit_path do |f| %>
      <table class="table table-borderless">
        <tr class="border-bottom border-gray pb-2 my-3">
          <th>シナリオ名</th>
          <td><%= f.text_field :scenario_name, size: "50x1" %></td>
        </tr>
        <tr class="border-bottom border-gray pb-2 mb-3">
          <th>タイトル</th>
          <td><%= f.collection_select(:title_id, Title.all, :id, :name, {}, {class:"select-box"}) %></td>
        </tr>
        <tr class="border-bottom border-gray pb-2 my-3">
          <th>メッセージ</th>
          <td><%= f.text_area :message, placeholder: recruit_message, size: "60x20" %></td>
        </tr>
        <tr>
          <th>募集状況</th>
          <td>
            <%= f.radio_button :recruit_status, true %>
            <%= f.label :recruit_status_true, "募集中" %>
            <%= f.radio_button :recruit_status, false %>
            <%= f.label :recruit_status_false, "募集終了" %>
          </td>
        </tr>
        <tr>
          <th></th>
          <td>
            <%= f.radio_button :status, 0 %>
            <%= f.label :status_published, "公開" %>
            <%= f.radio_button :status, 1 %>
            <%= f.label :recruit_status_draft, "下書き" %>
          </td>
        </tr>
        <tr class="pb-2-my-3">
          <th></th>
          <td>
            <div class="text-right">
              <%= f.hidden_field :recruit_status, :value => true %>
              <%= f.submit "更新", class: "btn btn-primary" %>
            </div>
          </td>
        </tr>
      </table>
    <% end %>
  </div>
</div>

app/views/admin/recruits/index.html.erb
<div class="container">
  <div class="d-flex align-items-center px-3 pt-3 mt-2">
    <h4 class="border-bottom border-primary border-3 page-title">メンバー募集</h4>
  </div>

  <div class="d-flex align-items-center px-3 pb-2 my-2">
    <div class="ml-auto">
      <%= form_tag({controller:"recruits",action:"index"}, method: :get) do %>
        <%= select_tag :search, options_from_collection_for_select(Title.all, :id, :name) %>
        <%= submit_tag '検索する' %>
      <% end %>
      <%= link_to "条件クリア", recruits_path, class: "btn btn-secondary mt-1" %>
    </div>
  </div>

  <div class="my-2 p-3 bg-white rounded shadow-sm">
    <table class="table">
      <thead class="thead-light">
        <tr>
          <th>ユーザー名</th>
          <th>シナリオ名</th>
          <th>タイトル</th>
          <th>更新日</th>
        </tr>
      </thead>
      <tbody>
        <% @recruits.each do |recruit| %>
          <tr>
            <td class="pt-2 pr-2">
              <%= link_to admin_user_path(recruit.user.id) do %>
                <%= image_tag recruit.user.get_profile_image.variant(resize: "60x60!") %>
                <%= recruit.user.name %>
              <% end %>
            </td>
            <td class="align-middle">
              <%= link_to admin_recruit_path(recruit.id) do %>
                <%= recruit.scenario_name %>
              <% end %>
            </td>
            <td class="align-middle">
              <span class="p-2 text-dark"><%= recruit.title.name %></span>
            </td>
            <td class="align-middle">
              <%= recruit.updated_at.strftime('%Y/%m/%d') %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    </div>
  </div>
</div>

app/views/admin/recruits/new.html.erb
<h1>Admin::Recruits#new</h1>
<p>Find me in app/views/admin/recruits/new.html.erb</p>

app/views/admin/recruits/show.html.erb
<div class="container mb-3">
  <div class="d-flex align-items-center p-3 my-2">
    <h4 class="border-bottom border-primary border-3 page-title">募集詳細</h4>
  </div>
  <div class="my-3 p-3 bg-white rounded shadow-sm">
    <%= image_tag @recruit.user.get_profile_image.variant(resize: "80x80!") %>　<%= @recruit.user.name %>
    <h3 class="d-inline ml-3"><%= @recruit.scenario_name %></h3>
      <span class="p-2 text-dark"><%= @recruit.title.name %></span>
    <p class="mt-3"><strong>
      <% if @recruit.recruit_status == true %>
        <span class="text-success">募集中</span>
      <% else %>
        <span class="text-secondary">募集終了</span>
      <% end %>
    </strong></p>
    <div class="mb-3">
      <h6 class="border-bottom border-gray pb-2 my-4"><strong>メッセージ</strong></h6>
      <%= safe_join(@recruit.message.split("\n"), tag(:br) ) %>
    </div>
    <%= link_to "編集", edit_admin_recruit_path(@recruit.id), class: "btn btn-secondary" %>
    <%= link_to "削除", admin_recruit_path(@recruit.id), method: :delete, class: "btn btn-danger", data: {confirm: "削除しますか？"} %>
  </div>

  <div class="align-items-center p-3 my-3 text-light bg-gray rounded shadow-sm">
    <p>コメント</p>
    <div class="row border-bottom border-gray p-2 my-4 mx-1">
      <% @recruit.comments.each do |comment| %>
        <div class="col-auto">
          <%= image_tag comment.user.get_profile_image.variant(resize: "60x60!") %><%= comment.user.name %>
        </div>
        <div class="col-auto">
          <%= safe_join(comment.comment.split("\n"),tag(:br)) %>
        </div>
        <div class="col-auto">
          <%= comment.updated_at.strftime("%Y/%m/%d %H:%M") %>
        </div>
        <div class="col-auto">
          <%= link_to "削除", admin_recruit_comment_path(comment.recruit, comment), method: :delete, data: {confirm: "削除しますか？"}, class: "btn btn-danger" %>
        </div>
    <% end %>
    </div>
  </div>
</div>