config/routes.rb
Rails.application.routes.draw do

  root to: "public/homes#top", as: 'top'

  devise_for :admins, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_scope :user do
    post 'public/guest_sign_in', to: 'public/sessions#guest_sign_in', as: 'guest_sign_in'
  end

  scope module: :public do
    resources :play_histores, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      resource :favorites, only: [:create, :destroy]
    end
    resources :recruits, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      resources :comments, only: [:create, :update, :destroy]
    end
    resources :users, only: [:index, :show, :edit, :update, :destroy]do
      resource :follows, only: [:create, :destroy]
      get 'followings' => 'follows#followings', as: 'followings'
      get 'followers' => 'follows#followers', as: 'followers'
    end

    get 'following_users' => 'follows#index', as: 'following_users'
    get 'drafts', to: 'recruits#drafts', as: 'drafts'
    get 'favorites', to: 'favorites#index', as: 'favorites'
    # get 'search_play_histores'=>'playHistores#search_play_histores', as: 'search_play_histores'
  #   post '/user/:/users/:user_id/follows'
  #   patch '/users/:user_id/follows'
  #   get '/users/confirm', to: 'users#confirm', as: 'confirm'
  #   patch '/users/cancel', to: 'users#cancel', as: 'cancel'

  end

  namespace :admin do
    resources :play_histores, only: [:index,:show, :edit, :update, :destroy]
    resources :titles, only: [:index, :create, :show, :edit, :update, :destroy]
    resources :users, only: [:index, :show, :edit, :update, :destroy]
    resources :recruits, only: [:index,:show,:edit, :update, :destroy] do
      resources :comments, only: [:destroy]
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, length: { minimum: 1, maximum: 20 }

  belongs_to :title, optional: true
  has_many :recruits, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :play_historys, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :follows, class_name: "Follow", foreign_key: "follower_id", dependent: :destroy
  has_many :followeds, class_name: "Follow", foreign_key: "followee_id", dependent: :destroy

  has_many :following_users, through: :follows, source: :followee
  has_many :follower_users, through: :followees, source: :follower

  enum main_playstyle: { gm_only: 0, gm_trend: 1, both: 2, player_trend: 3, player_only: 4}

  has_one_attached :profile_image

  def get_profile_image
    unless profile_image.attached?
     file_path = Rails.root.join('app/assets/images/user_default.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'user_default.jpg', content_type: 'image/jpeg')
    end
    profile_image
  end

  def follow(user_id)
    follows.create(followee_id: user_id)
  end

  def unfollow(user_id)
    follows.find_by(followee_id: user_id).destroy
  end

  def following?(user)
    following_users.include?(user)
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲスト"
    end
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @play_histores = PlayHistory.where(user_id: params[:id])
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to admin_users_path
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/edit.html.erb
<div class="container">
  <div class="d-flex align-items-center p-3 my-2">
    <h4 class="border-bottom border-primary border-3 page-title">ユーザー編集</h4>
  </div>
  <div class="first-form mx-auto">
    <div class="my-3 p-4 bg-white rounded shadow-sm">
      <%= form_with model: @user, url: user_path(@user.id) do |f| %>
        <form>
          <div class="row mb-4">
            <label for="inputEmail" class="col-sm-3 col-form-label">ユーザー画像</label>
            <div class="col-sm-8">
              <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>
            </div>
          </div>
          <div class="row mb-4 mt-2">
            <label for="inputEmail" class="col-sm-3 col-form-label">ユーザー名</label>
            <div class="col-sm-7">
              <%= f.text_field :name, autofocus: true, class: "form-control" %>
            </div>
          </div>
          <div class="row mb-4">
            <label for="inputEmail" class="col-sm-3 col-form-label">Eメール</label>
            <div class="col-sm-7">
              <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "form-control" %>
            </div>
          </div>
          <div class="row mb-4">
            <label for="inputPassword" class="col-sm-3 col-form-label">メインタイトル</label>
            <div class="col-sm-7">
              <%= f.collection_select(:title_id, Title.all, :id, :name, {}, {class:"select-box"}) %>
            </div>
          </div>
          <div class="row mb-4">
            <label for="inputPassword" class="col-sm-3 col-form-label">プレイスタイル</label>
            <div class="col-sm-7">
              <%= f.radio_button :main_playstyle, User.main_playstyles.key(0), checked: true %>
              <%= f.label :main_play_style_gm_only, User.main_playstyles_i18n[:gm_only] %>
              <%= f.radio_button :main_playstyle, User.main_playstyles.key(1) %>
              <%= f.label :main_play_style_gm_trend, User.main_playstyles_i18n[:gm_trend] %><br>
              <%= f.radio_button :main_playstyle, User.main_playstyles.key(2)%>
              <%= f.label :main_play_style_both, User.main_playstyles_i18n[:both] %>
              <%= f.radio_button :main_playstyle, User.main_playstyles.key(3) %>
              <%= f.label :main_play_style_player_trend, User.main_playstyles_i18n[:player_trend] %><br>
              <%= f.radio_button :main_playstyle, User.main_playstyles.key(4) %>
              <%= f.label :main_play_style_player_only, User.main_playstyles_i18n[:player_only] %>
            </div>
          </div>
          <div class="row mb-4">
            <label for="inputPassword" class="col-sm-3 col-form-label">自己紹介</label>
            <div class="col-sm-6 h-50">
              <%= f.text_area :message, size: "40x10" %>
            </div>
          </div>
          <div class="row mb-4">
            <label for="inputPassword" class="col-sm-3 col-form-label">公開設定</label>
            <div class="col-sm-6">
              <%= f.radio_button :is_private, false %>
              <%= f.label :is_private_false, "公開" %>
              <%= f.radio_button :is_private, true %>
              <%= f.label :is_private_true, "非公開" %>
            </div>
          </div>
          <%= f.submit '変更を保存', class: "btn btn-info" %>
        </form>
      <% end %>
    </div>
    <%= link_to "アカウント削除", user_path, method: :delete, class: "btn btn-danger", data: {confirm: "本当にアカウントを削除しますか？"} %>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="container">
  <div class="d-flex align-items-center p-3 my-2">
    <h4 class="border-bottom border-primary border-3 page-title">ユーザー一覧</h4>
    <div class="ml-auto">
      <%= form_tag({controller:"users",action:"index"}, method: :get) do %>
      <%= text_field_tag :search, "", placeholder: "ユーザー名" %>
      <%= submit_tag '検索する' %>
    <% end %>
    </div>
  </div>

  <div class="my-2 p-3 bg-white rounded shadow-sm">
    <table class="table">
      <thead class="thead-light">
        <tr>
          <th>ユーザー名</th>
          <th>メインプレイ</th>
          <th>登録日</th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td class="pt-2">
              <%= link_to admin_user_path(user.id) do %>
                <%= image_tag user.get_profile_image.variant(resize: "60x60!") %>
                <%= user.name %>
              <% end %>
            </td>
            <td class="align-middle">
              <% if user.title_id == nil %>
                <span class="p-2 text-dark">未設定</span>
              <% else %>
                <span class="p-2 text-dark"><%= user.title.name %></span>
              <% end %>

              <% if user.main_playstyle == nil %>
                プレイスタイル：未設定
              <% else %>
                プレイスタイル：<%= user.main_playstyle_i18n %>
              <% end %>
            </td>
            <td><%= user.created_at.strftime('%Y/%m/%d') %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    </div>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="container">
  <div class="d-flex align-items-center p-3 my-3 text-light bg-gray rounded shadow-sm">
    <%= image_tag @user.get_profile_image.variant(resize: "100x100!") %>
    <h3>
       <%= @user.name %>
      <% if @user.is_private == true %>
        <i class="fa-solid fa-lock"></i>
      <% end %>
    </h3>
    <div class="ml-2">
      <%= link_to edit_admin_user_path(@user.id), class: "btn btn-outline-light" do %>
        <i class="fa-solid fa-gear"></i> 編集
      <% end %>
    </div>
    <div class="ml-auto">
      <%= link_to following_users_path, class: "btn btn-light" do %>
        <i class="fa-regular fa-star"></i> フォローユーザー
      <% end %>
    </div>
  </div>

  <div class="my-3 p-3 bg-white rounded shadow-sm">
    <h6 class="border-bottom border-gray pb-2 mb-3"><strong>メインプレイ</strong></h6>
    <% if @user.title_id == nil %>
      <p><span class="p-2 text-dark">未設定</span></p>
    <% else %>
      <p><span class="p-2 text-dark"><%= @user.title.name %></span></p>
    <% end %>

    <p>
      プレイスタイル：
      <% if @user.main_playstyle == nil %>
        未設定
      <% else %>
        <%= @user.main_playstyle_i18n %>
      <% end %>
    </p>

    <h6 class="border-bottom border-gray py-2 my-2"><strong>自己紹介</strong></h6>

    <p class="text-dark p-3">
      <% if @user.message == nil %>
        よろしくお願いします！
      <% else %>
        <%= safe_join(@user.message.split("\n"), tag(:br) )  %>
      <% end %>
    </p>
  </div>
  <div class="my-3 p-3 bg-white rounded shadow-sm">
    <h6 class="border-bottom border-gray pb-2 mb-3"><strong><%= @user.name %>のプレイ履歴</strong></h6>
    <table class="table">
      <thead class="thead-light">
        <tr>
          <th>ユーザー</th><th>シナリオ名</th><th>タイトル</th><th>担当</th><th>登録日</th>
        </tr>
      </thead>
      <tbody>
        <% @play_histores.each do |play_history| %>
          <tr>
            <td class="align-middle"><%= link_to admin_user_path(play_history.user_id) do %>
                <%= image_tag play_history.user.get_profile_image.variant(resize: "60x60!") %>
                <%= play_history.user.name %>
              <% end %>
            </td>
            <td class="align-middle">
              <%= link_to admin_play_histore_path(play_history.id) do %>
                <%= play_history.scenario_name %>
              <% end %>
            </td>
            <td class="align-middle">
              <span class="p-2 text-dark"><%= play_history.title.name %></span>
            </td>
            <td class="align-middle"><%= play_history.play_style_i18n %></td>
            <td class="align-middle"><%= play_history.created_at.strftime('%Y/%m/%d') %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>