config/routes.rb
Rails.application.routes.draw do

  root to: "public/homes#top", as: 'top'

  devise_for :admins, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_scope :user do
    post 'public/guest_sign_in', to: 'public/sessions#guest_sign_in', as: 'guest_sign_in'
  end

  scope module: :public do
    resources :play_histores, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      resource :favorites, only: [:create, :destroy]
    end
    resources :recruits, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      resources :comments, only: [:create, :update, :destroy]
    end
    resources :users, only: [:index, :show, :edit, :update, :destroy]do
      resource :follows, only: [:create, :destroy]
      get 'followings' => 'follows#followings', as: 'followings'
      get 'followers' => 'follows#followers', as: 'followers'
    end

    get 'following_users' => 'follows#index', as: 'following_users'
    get 'drafts', to: 'recruits#drafts', as: 'drafts'
    get 'favorites', to: 'favorites#index', as: 'favorites'
    # get 'search_play_histores'=>'playHistores#search_play_histores', as: 'search_play_histores'
  #   post '/user/:/users/:user_id/follows'
  #   patch '/users/:user_id/follows'
  #   get '/users/confirm', to: 'users#confirm', as: 'confirm'
  #   patch '/users/cancel', to: 'users#cancel', as: 'cancel'

  end

  namespace :admin do
    resources :play_histores, only: [:index,:show, :edit, :update, :destroy]
    resources :titles, only: [:index, :create, :show, :edit, :update, :destroy]
    resources :users, only: [:index, :show, :edit, :update, :destroy]
    resources :recruits, only: [:index,:show,:edit, :update, :destroy] do
      resources :comments, only: [:destroy]
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :comment, presence: true
  
  belongs_to :user
  belongs_to :recruit
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :play_history
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followee, class_name: "User"
end

app/models/play_history.rb
class PlayHistory < ApplicationRecord
  validates :scenario_name, presence: true, length: { minimum: 1, maximum: 40 }
  validates :play_style, presence: true
  # validates :is_active, presence: true

  belongs_to :user
  belongs_to :title
  has_many :favorites, dependent: :destroy
  enum play_style: {gm: 0, player: 1}
  enum status: { published: 0, draft: 1 }

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
end

app/models/recruit.rb
class Recruit < ApplicationRecord
  validates :scenario_name, presence: true, length: { minimum: 1, maximum: 40 }
  validates :message, presence: true

  enum status: { published: 0, draft: 1 }

  belongs_to :user
  belongs_to :title
  has_many :comments, dependent: :destroy
end

app/models/title.rb
class Title < ApplicationRecord
  validates :name, presence: true
  
  has_many :users
  has_many :recruits
  has_many :play_histores
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, length: { minimum: 1, maximum: 20 }

  belongs_to :title, optional: true
  has_many :recruits, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :play_historys, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :follows, class_name: "Follow", foreign_key: "follower_id", dependent: :destroy
  has_many :followeds, class_name: "Follow", foreign_key: "followee_id", dependent: :destroy

  has_many :following_users, through: :follows, source: :followee
  has_many :follower_users, through: :followees, source: :follower

  enum main_playstyle: { gm_only: 0, gm_trend: 1, both: 2, player_trend: 3, player_only: 4}

  has_one_attached :profile_image

  def get_profile_image
    unless profile_image.attached?
     file_path = Rails.root.join('app/assets/images/user_default.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'user_default.jpg', content_type: 'image/jpeg')
    end
    profile_image
  end

  def follow(user_id)
    follows.create(followee_id: user_id)
  end

  def unfollow(user_id)
    follows.find_by(followee_id: user_id).destroy
  end

  def following?(user)
    following_users.include?(user)
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲスト"
    end
  end

end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController

  def destroy
    Comment.find(params[:id]).destroy
    redirect_to admin_recruit_path(params[:recruit_id])
  end

end

app/controllers/admin/titles_controller.rb
class Admin::TitlesController < ApplicationController
  def index
    @titles = Title.all
    @title = Title.new
  end
  
  def create
    @titles = Title.all
    @title = Title.new(title_params)
    if @title.save
      redirect_to admin_titles_path
    else
      render :index
    end
  end

  def edit
    @title = Title.find(params[:id])
  end
  
  
  def update
    @title = Title.find(params[:id])
    if @title.update(title_params)
      redirect_to admin_titles_path
    else
      render :index
    end
  end
  
  def destroy
    title = Title.find(params[:id])
    title.destroy
    redirect_to admin_titles_path
  end
  
  private
  
  def title_params
    params.require(:title).permit(:name)
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @play_histores = PlayHistory.where(user_id: params[:id])
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to admin_users_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/play_histores_helper.rb
module Admin::PlayHistoresHelper
end

app/helpers/admin/recruits_helper.rb
module Admin::RecruitsHelper
end

app/helpers/admin/titles_helper.rb
module Admin::TitlesHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Takukomyu</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/e0fb69895e.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <style>
    .btn-login {
        background-color: rgb(21, 190, 174);
        color: rgb(255, 255, 255);
      }

      .btn-login:hover {
        background-color: rgb(255, 255, 255);
        color: rgb(21, 190, 174);
        border-color: rgb(21, 190, 174);
      }

      .btn-sign_up {
        background-color: rgb(200, 150, 120);
        color: rgb(255, 255, 255);
      }

      .btn-sign_up:hover {
        background-color: rgb(255, 255, 255);
        color: rgb(200, 150, 120);
        border-color: rgb(200, 150, 120);
      }

     .btn-favorited {
        background-color: rgb(250, 124, 193);
        color: rgb(255, 255, 255);
      }

      .btn-favorited:hover {
        background-color: rgb(255, 255, 255);
        color: rgb(250, 124, 193);
        border-color: rgba(250, 124, 193);
      }

      .btn-favorit {
        background-color: rgb(255, 255, 255);
        color: rgb(250, 124, 193);
        border-color: rgba(250, 124, 193);
      }

      .btn-favorit:hover {
        background-color: rgb(250, 124, 193);
        color:rgb(255, 255, 255);
      }

      .btn-draft {
        background-color: rgb(35, 220, 220);
        color: rgb(255, 255, 255);
        border-color: rgb(35, 220, 220);
      }

      .btn-draft:hover {
        background-color: rgba(35, 220, 220, 0.8);
        color: rgb(255, 255, 255);
        border-color: rgba(35, 220, 220, 0.8);
      }

      .btn-favorit {
        background-color: rgb(255, 255, 255);
        color: rgb(250, 124, 193);
        border-color: rgba(250, 124, 193);
      }

      .btn-favorit:hover {
        background-color: rgb(250, 124, 193);
        color:rgb(255, 255, 255);
      }

      .btn-admin-login {
        background-color: rgb(106, 108, 247);
        color: rgb(255, 255, 255);
        border-color: rgba(106, 108, 247);
      }

      .btn-admin-login:hover {
        background-color: rgb(255, 255, 255);
        color: rgb(106, 108, 247);
        border-color: rgba(106, 108, 247);
      }

    </style>
  </head>

  <body style="background-color: #F5F5F5;">
    <header class="sticky-top">
      <div class="cotainer">
        <nav class="navbar navbar-expand-sm navbar-dark" style="background-color:#AAAAAA;">
        <button class="navbar-toggler" type="button" data-toggler="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand page-title" href="/">卓コミュ</a>
        <div class="collapse navbar-collapse justify-content-end">
          <ul class="navbar-nav">
            <% if user_signed_in? %>
              <li class="nav-item text-dark">
                <%= link_to user_path(current_user.id), class: 'nav-link text-dark' do %>
                  <%= image_tag current_user.get_profile_image.variant(resize: "50x50!") %>
                   マイページ
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to("使い方", top_path(anchor: "about"), class: "nav-link text-dark") %>
              </li>
              <li class="nav-item">
                <%= link_to "いいね一覧", favorites_path, class: "nav-link text-dark" %>
              </li>
              <li class="nav-item">
                <%= link_to 'プレイ履歴', play_histores_path, class: 'nav-link text-dark' %>
              </li>
              <li class="nav-item">
                <%= link_to 'メンバー募集', recruits_path, class: 'nav-link text-dark' %>
              </li>
              <li class="nav-item">
                <%= link_to 'ユーザー検索', users_path, class: 'nav-link text-dark' %>
              </li>
              <li class="nav-item">
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'nav-link text-dark' %></li>
              </li>
            <% elsif admin_signed_in? %>
              <li class="nav-item">
                <%= link_to 'タイトル一覧', admin_titles_path, class: 'nav-link text-dark' %>
              </li>
              <li class="nav-item">
                <%= link_to 'プレイ履歴', admin_play_histores_path, class: 'nav-link text-dark' %>
              </li>
              <li class="nav-item">
                <%= link_to 'メンバー募集', admin_recruits_path, class: 'nav-link text-dark' %>
              </li>
              <li class="nav-item">
                <%= link_to 'ユーザー検索', admin_users_path, class: 'nav-link text-dark' %>
              </li>
              <li class="nav-item">
                <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link text-dark' %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to("使い方", top_path(anchor: "about"), class: "nav-link text-dark") %>
              <li class="nav-item">
                <%= link_to 'ログイン', new_user_session_path, class: 'nav-link text-dark' %>
              </li>
              <li class="nav-item">
                <%= link_to "新規登録", new_user_registration_path, class: 'nav-link text-dark' %>
              </li>
              <li class="nav-item">
                <%= link_to 'プレイ履歴', play_histores_path, class: 'nav-link text-dark' %>
              </li>
              <li class="nav-item">
                <%= link_to 'メンバー募集', recruits_path, class: 'nav-link text-dark' %>
              </li>
              <li class="nav-item">
                <%= link_to 'ユーザー検索', users_path, class: 'nav-link text-dark' %>
              </li>
            <% end %>
          </ul>
        </div>
      </nav>
    </div>
  </header>
  <%= render 'public/shared/flash_message' %>
  <main>
    <%= yield %>
  </main>
  </body>
</html>